FROM --platform=linux/amd64 nvidia/cuda:11.3.1-cudnn8-devel-ubuntu20.04

USER root
ENV DEBIAN_FRONTEND=noninteractive

RUN apt update && apt install --no-install-recommends -y coinor-cbc git wget python3-pip && rm -rf /var/lib/apt/lists/*
RUN wget https://together-distro-packages.s3.us-west-2.amazonaws.com/linux/x86_64/bin/together-node-latest -O /usr/local/bin/together-node && \
    chmod +x /usr/local/bin/together-node

RUN useradd -m user

USER user
WORKDIR /home/user

ENV PATH /home/user/.local/bin:$PATH

RUN pip install --no-cache-dir --upgrade pip && \
    pip install --no-cache-dir cupy-cuda113 && \
    pip install --no-cache-dir jaxlib==0.3.22+cuda113.cudnn820 -f https://alpa-projects.github.io/wheels.html && \
    pip install --no-cache-dir torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/cu113

RUN pip3 install --no-cache-dir \
      git+https://github.com/huggingface/accelerate.git@5b9c5881b687af1c7a8807aa20ac4a6b36f085c9 \
      alpa \
      bitsandbytes \
      einops \
      fastapi \
      jinja2 \
      omegaconf \
      sentencepiece \
      together_worker \
      uvicorn \
      git+https://github.com/huggingface/peft.git@b1bafca3332c7ff21dcb92892df38a04d3b43d56 \
      scipy \
      'llm_serving @ git+https://github.com/alpa-projects/alpa#subdirectory=examples' \
      'transformers @ git+https://github.com/togethercomputer/transformers_port'

COPY cfg-neoxt-local.yaml /home/user/cfg-neoxt.yaml
COPY cfg-neoxt-local-8bit.yaml /home/user/cfg-neoxt-8bit.yaml
COPY cfg-neoxt-retrieval-local.yaml /home/user/cfg-neoxt-retrieval.yaml
COPY cfg-hf-local.yaml /home/user/cfg-hf.yaml

ENV PYTHONUNBUFFERED=1

RUN mkdir -p /home/user/app
COPY . /home/user/app
WORKDIR /home/user/app
