FROM nvidia/cuda:11.7.0-cudnn8-devel-ubuntu20.04

# init workdir
RUN mkdir -p /build
WORKDIR /build

# install common tool & conda
RUN apt update && \
    apt install wget -y && \
    apt install git -y && \
    apt install vim -y && \
    wget --quiet https://repo.anaconda.com/archive/Anaconda3-2022.05-Linux-x86_64.sh -O ~/anaconda.sh && \
    /bin/bash ~/anaconda.sh -b -p /opt/conda && \
    rm ~/anaconda.sh && \
    mkdir -p /opt/conda/envs/alpa && \
    ln -s /opt/conda/etc/profile.d/conda.sh /etc/profile.d/conda.sh && \
    echo ". /opt/conda/etc/profile.d/conda.sh" >> ~/.bashrc
# echo ". /opt/conda/etc/profile.d/conda.sh" >> ~/.bashrc && \
# echo "conda activate base" >> ~/.bashrc

RUN mkdir -p /safari-internal
COPY safari-internal /safari-internal

# install conda alpa env
RUN . /opt/conda/etc/profile.d/conda.sh && \
    conda create --name alpa python=3.8 -y && \
    conda activate alpa && \
    apt install coinor-cbc -y && \
    pip3 install --upgrade pip && \
    pip3 install cupy-cuda117 && \
    pip3 install alpa && \
    pip3 install --upgrade "jax[cuda11_pip]" -f https://storage.googleapis.com/jax-releases/jax_cuda_releases.html && \
    pip3 install together_worker && \
    pip3 install transformers && \
    pip3 install fastapi uvicorn omegaconf jinja2 einops && \
    pip3 install torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/cu117  && \
    pip3 install flash-attn==1.0.2 && \
    cd /build && \
    git clone https://github.com/alpa-projects/alpa.git && \
    cd alpa/examples && \
    pip3 install -e . && \
    pip3 install sentencepiece && \
    pip3 install accelerate && \
    echo "conda activate alpa" >> ~/.bashrc && \
    pip3 install triton && \
    cd /safari-internal && pip3 install --trusted-host pypi.python.org -r requirements.txt && \
    cd /safari-internal/csrc/fftconv && python setup.py install

RUN wget https://together-distro-packages.s3.us-west-2.amazonaws.com/linux/x86_64/bin/together-node-latest -O /usr/local/bin/together-node && \
    chmod +x /usr/local/bin/together-node
COPY cfg-neoxt-local.yaml /home/user/cfg-neoxt.yaml
ENV PATH /opt/conda/condabin/conda/bin:$PATH
ENV HOME=/home/user
ENV PYTHONUNBUFFERED=1

RUN mkdir -p /app
COPY . /app
WORKDIR /app
