FROM zxdu20/glm-cuda112

RUN pip3 install together_worker && \
    pip3 install SwissArmyTransformer && \
    pip3 install icetk

RUN wget https://together-distro-packages.s3.us-west-2.amazonaws.com/linux/x86_64/bin/together-node-latest -O /usr/local/bin/together-node && \
    chmod +x /usr/local/bin/together-node
ENV PATH /opt/conda/condabin/conda/bin:$PATH

RUN mkdir -p /app
COPY . /app
WORKDIR /app